UserId:
  name: id
  in: path
  description: User ID
  required: true
  schema:
    type: string

UserEmail:
  name: email
  in: path
  description: User email address
  required: true
  schema:
    type: string
    format: email

LimitQuery:
  name: limit
  in: query
  description: Maximum number of users to return
  required: false
  schema:
    type: integer
    default: 10000
    minimum: 1
    maximum: 10000

PageQuery:
  name: page
  in: query
  description: Page number (0-indexed)
  required: false
  schema:
    type: integer
    default: 0
    minimum: 0

SizeQuery:
  name: size
  in: query
  description: Number of items per page
  required: false
  schema:
    type: integer
    default: 20
    minimum: 1
    maximum: 100
